### ISSUE TITLE
RMarkdown formatting questions?

### ISSUE THREAD

**Issue by bwiernik** [USF-Psych-DataSci-2020/Discussion#9]
Hi folks,

The topics for this week are reproducibility, good coding practice, and using RMarkdown to produce real manuscripts, reports, papers, and other products. For the last part, we'll cover controlling the output formatting in HTML (e.g., customizing tables; hiding code), outputting to PDF, and outputting to Word (and pulling documents back from Word to R when you are working with a collaborator). 

Are there any specific things you've wanted to know how to do in RMarkdown output that you would like me to also cover?

**Comment by alliechoate** [comment]
What's a good way to reduce spacing between code chunks and text above the chunk? (Putting an example below since that is kind of a vague question).


**Code below is for x:**
```{r
#code here blahblahblah
describe(x)
```
If the above code chunk is in Rmarkdown, I've found that rendering the Rmarkdown to at least  .html typically results in an unnecessary amount of space between the text above the code chunk and the actual code in the chunk. I know you can set knitr options to 'highlight = FALSE' and that seems to solve the problem I am referring to, though by adding that it messes with some other functionality aspects of Rmarkdown that I like (i.e., code folding doesn't seem to work properly). Any suggestions on how to reduce spacing would be very much appreciated! :)

**Comment by bwiernik** [comment]
This is in the HTML formatting section of this week's notes as an example of providing custom CSS in your script (personally, I suggest leaving the whitespace in place; it helps improve readability).
